title: Ewakened
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Kent Fenwick writes here about tech, parenting, startups, fintech and web3.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ewakened.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kentf
github_username:  kent

# Build settings
theme: minima
plugins:
  - jekyll-feed
